### ISSUE TITLE
Feedback for Lab Report 1

### ISSUE THREAD

**Issue by ShuhangXu** [SGJR247/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Please show more explanation in Optimizing Remote Running. Try to find how to use semicolons to save time and optimize your code and give an example. If you still have further questions, please feel free to refer to the end of Lab1 or attend our office hour.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by SGJR247** [comment]
1. What do you mean by "Link to this issue" when it comes to submitting a regrade request on Gradescope?
2. Does the "Link to my published lab report page" mean I should use a link that leads to the most up-to-date version of that webpage?

**Comment by ShuhangXu** [comment]
It's the same as your first submission. The first line is the link of your edited lab report page and the second line should be the link of your repository like https://github.com/SGJR247/cse15l-lab-reports. Please feel free to leave your further comments here.
